### ISSUE TITLE
Breakdance 2.5-beta1: Earlier installed custom fonts lead to a fatal error

### ISSUE THREAD

**Issue by mirkoschubert** [soflyy/breakdance-bugs#1241]
If you upgrade a Breakdance website where you have used custom fonts (in my case a string from the CSS font stack) to the new version 2.5-beta1 the Breakdance builder won't open with an error and later on the complete website gets the same fatal error.

Steps:
1. Create a website with Breakdance 2.4 or earlier
2. In Breakdance builder go to Settings and set up custom fonts (as a string such as "Arial, Verdana, sans-serif")
3. Upgrade to Breakdance 2.5-beta1
4. Open Breakdance builder (error appears)
5. Close the builder
6. Do anything else on the wp-admin (I deactivated a custom plugin for debugging)
7. The whole website outputs the error and is not usable anymore.

The error message is:
```
Uncaught Error: Too few arguments to function Breakdance\Fonts\FontsController::registerFontAtTheStart(), 5 passed in /www/htdocs/w01802b5/breakdance.mirkoschubert.de/wp-content/plugins/breakdance/plugin/fonts/integrations/custom/load-custom-fonts.php on line 20 and exactly 6 expected
in /www/htdocs/w01802b5/breakdance.mirkoschubert.de/wp-content/plugins/breakdance/plugin/fonts/fonts.php on line 155

Call stack:

Breakdance\Fonts\FontsController::registerFontAtTheStart('custom_font_helvetica_neue', '"Helvetica Neue"', 'Helvetica Neue', 'Verdana, sans-serif', array)
wp-content/plugins/breakdance/plugin/fonts/integrations/custom/load-custom-fonts.php:20
Breakdance\CustomFonts\loadCustomFonts(Breakdance\Fonts\FontsController)
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters(NULL, array)
wp-includes/class-wp-hook.php:348
WP_Hook::do_action(array)
wp-includes/plugin.php:517
do_action('breakdance_register_fonts', Breakdance\Fonts\FontsController)
wp-content/plugins/breakdance/plugin/breakdance-oxygen/actions-filters.php:10
bdox_run_action('breakdance_register_fonts', Breakdance\Fonts\FontsController)
wp-content/plugins/breakdance/plugin/fonts/fonts.php:111
Breakdance\Fonts\FontsController::__construct()
wp-content/plugins/breakdance/plugin/util/singleton.php:16
Breakdance\Fonts\FontsController::getInstance()
wp-content/plugins/breakdance/plugin/fonts/fonts.php:223
Breakdance\Fonts\process_font('custom_font_helvetica_neue')
/tmp/breakdance-3e7ce347/twig-auto-generated-cache/aa/aaba1089f9b6102e36de73bdfe590f91.php:121
__TwigTemplate_75f5a45038f003ebc23a43ee432ba96c::doDisplay(array, array)
wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Template.php:394
Breakdance\L\V\T\Template::displayWithErrorHandling(array, array)
wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Template.php:367
Breakdance\L\V\T\Template::display(array)
wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Template.php:379
Breakdance\L\V\T\Template::render(array, array)
wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/TemplateWrapper.php:40
Breakdance\L\V\T\TemplateWrapper::render(array)
wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Environment.php:280
Breakdance\L\V\T\Environment::render('bf090263f4e4abe2e2e402fffde546542f42a851', array)
wp-content/plugins/breakdance/plugin/render/twig.php:223
Breakdance\Render\Twig::runTwig(' {% import "macros.t...or %} {% endif %} ', array)
wp-content/plugins/breakdance/plugin/render/renderer.php:407
Breakdance\Render\{closure}('', array)
array_reduce(array, Closure, '')
wp-content/plugins/breakdance/plugin/render/renderer.php:383
Breakdance\Render\cssForGlobalStyles(array, '{% if isBaseBreakpoi...for %} {% endif %} ', array)
wp-content/plugins/breakdance/plugin/render/cache.php:219
Breakdance\Render\generateCacheForGlobalSettings()
wp-content/plugins/breakdance/plugin/render/cache.php:143
Breakdance\Render\getGlobalSettingsCache()
wp-content/plugins/breakdance/plugin/render/capture-wordpress-output.php:23
Breakdance\Render\{closure}('')
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters(NULL, array)
wp-includes/class-wp-hook.php:348
WP_Hook::do_action(array)
wp-includes/plugin.php:517
do_action('init')
wp-settings.php:727
require_once('/www/htdocs/w01802b5...t.de/wp-settings.php')
wp-config.php:104
require_once('/www/htdocs/w01802b5...ert.de/wp-config.php')
wp-load.php:50
require_once('/www/htdocs/w01802b5...ubert.de/wp-load.php')
wp-admin/admin.php:35
```

You can also check [breakdance.mirkoschubert.de](https://breakdance.mirkoschubert.de).
I couldn't check if uploading custom font files would get to the same error, because my testing website is down. But I think it should since it may use the same function.

Technical Information:
 - Breakdance version: 2.5-beta1
 - WordPress: 6.8.1 (current)
 - PHP: 8.3
 - Browser: Brave 1.79.126 (current)
 - OS: macOS 15.5 (current)
 - Error reporting is on, but it doesn't matter.

**Comment by Sonoboomer** [comment]
Same with me after upgrading from breakdance 2.4 to 2.5.0 beta1.

Fehlermeldung: Uncaught ArgumentCountError: Too few arguments to function Breakdance\Fonts\FontsController::registerFontAtTheStart(), 5 passed in /homepages/40/d985904188/htdocs//wp-content/plugins/breakdance/plugin/fonts/integrations/custom/load-custom-fonts.php on line 20 and exactly 6 expected in /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/fonts/fonts.php:155
Stack trace:
#0 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/fonts/integrations/custom/load-custom-fonts.php(20): Breakdance\Fonts\FontsController->registerFontAtTheStart()
#1 /homepages/40/d985904188/htdocs/wp-includes/class-wp-hook.php(324): Breakdance\CustomFonts\loadCustomFonts()
#2 /homepages/40/d985904188/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /homepages/40/d985904188/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/breakdance-oxygen/actions-filters.php(10): do_action()
#5 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/fonts/fonts.php(111): bdox_run_action()
#6 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/util/singleton.php(16): Breakdance\Fonts\FontsController->__construct()
#7 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/fonts/fonts.php(223): Breakdance\Fonts\FontsController::getInstance()
#8 /tmp/breakdance-00118139/twig-auto-generated-cache/aa/aaba1089f9b6102e36de73bdfe590f91.php(121): Breakdance\Fonts\process_font()
#9 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Template.php(394): __TwigTemplate_75f5a45038f003ebc23a43ee432ba96c->doDisplay()
#10 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Template.php(367): Breakdance\Lib\Vendor\Twig\Template->displayWithErrorHandling()
#11 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Template.php(379): Breakdance\Lib\Vendor\Twig\Template->display()
#12 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/TemplateWrapper.php(40): Breakdance\Lib\Vendor\Twig\Template->render()
#13 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/lib/mozart-scoped-psr4/Twig/Environment.php(280): Breakdance\Lib\Vendor\Twig\TemplateWrapper->render()
#14 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/render/twig.php(223): Breakdance\Lib\Vendor\Twig\Environment->render()
#15 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/render/renderer.php(407): Breakdance\Render\Twig->runTwig()
#16 [internal function]: Breakdance\Render\{closure}()
#17 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/render/renderer.php(383): array_reduce()
#18 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/render/cache.php(219): Breakdance\Render\cssForGlobalStyles()
#19 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/render/cache.php(143): Breakdance\Render\generateCacheForGlobalSettings()
#20 /homepages/40/d985904188/htdocs/wp-content/plugins/breakdance/plugin/render/capture-wordpress-output.php(23): Breakdance\Render\getGlobalSettingsCache()
#21 /homepages/40/d985904188/htdocs/wp-includes/class-wp-hook.php(324): Breakdance\Render\{closure}()
#22 /homepages/40/d985904188/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#23 /homepages/40/d985904188/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#24 /homepages/40/d985904188/htdocs/wp-settings.php(727): do_action()
#25 /homepages/40/d985904188/htdocs/wp-config.php(100): require_once('/homepages/40/d...')
#26 /homepages/40/d985904188/htdocs/wp-load.php(50): require_once('/homepages/40/d...')
#27 /homepages/40/d985904188/htdocs/wp-admin/admin.php(35): require_once('/homepages/40/d...')
#28 /homepages/40/d985904188/htdocs/wp-admin/plugins.php(10): require_once('/homepages/40/d...')
#29 {main}
  thrown

Having sent this to the breakdance support team the answer was as expected: 
"Based on the information you provided, it sounds like something is breaking at the server level.
Please follow the steps outlined here https://breakdance.com/documentation/troubleshooting/troubleshooting-500-50x-errors/.
If you're unable to resolve the error yourself, please see step 4 for all of the information we will require to assist you with this. Once you've provided that information, we'll investigate further."

In WP backend the breakdance menu has disappeared, I deactivated and reactivated it, no success. Now I´m thinking about deleting breakdance via ftp and try to install the stable version 2.4.

Any comments on this procedure or better ideas to solve the issue?

**Comment by bytewerk-dev** [comment]
On a brand new install with 2.5-beta1 it's also not possible to install Adobe font sets. When adding the typekit css url Breakdance throws a 500 error.

**Comment by Sonoboomer** [comment]
In the meanwhile I found a workaround:
1.) Deactivate and delete breakdance 2.5.0 beta 1 via ftp (FileZilla)
2.) Install and activate the stable version breakdance 2.4.
3.) Deactivate "get beta versions" in breakdance settings.
Seems that there is a also problem with the plugin OMGF with breakdance. With breakdance version 2.4 it seems to work fine. Had no data losses. Site is online again.

**Comment by breakdancemoderator** [comment]
This has been addressed in [Breakdance 2.5 Beta 2](https://breakdance.com/breakdance-2-5-beta-2-now-available/), which is available for [beta testing](https://breakdance.com/documentation/advanced/enable-beta-updates/).
